scripts:
    - name: Get Flutter packages
      script: |
        flutter pub get
    - name: Ensure GoogleService-Info.plist is in project
      script: |
        cd ios
        # Check if GoogleService-Info.plist exists
        if [ -f "Runner/GoogleService-Info.plist" ]; then
          echo "GoogleService-Info.plist found"
          # Add to Xcode project if not already added
          if ! grep -q "GoogleService-Info.plist" Runner.xcodeproj/project.pbxproj; then
            echo "Adding GoogleService-Info.plist to Xcode project..."
            # This is a simplified approach - in practice you might need to use Xcode or a tool
            echo "Note: GoogleService-Info.plist should be manually added to Xcode project"
          fi
        else
          echo "Warning: GoogleService-Info.plist not found"
        fi
    - name: Build for iOS Simulator
      script: |
        flutter build ios --debug \
          --no-codesign \
          --simulator
